version: '3.4'

services:

  client:
    build:
      context: .
      target: build-node
    command: npm run dev
    volumes:
      - .:/home/node/app
      # node_modules is not shared with the host
      - /home/node/app/node_modules
      - client:/home/node/app/client/dist

  # Postgres
  # db:
  #   image: postgres:13.2-alpine
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data/
  #     - .data/db_dumps:/db_dumps
  #   environment:
  #     - POSTGRES_DB={{ project_name }}
  #     - POSTGRES_PASSWORD=postgres

  app:
    <<: &COMMON
      build:
        context: .
        target: build-python
      # Postgres
      # depends_on:
      #   - db
      environment:
        - DEBUG=true
        # Postgres
        # - DATABASE_URL=postgres://postgres:postgres@db:5432/{{ project_name }}
    stdin_open: true
    tty: true
    restart: on-failure
    volumes:
      - .:/app
      - /app/.venv
      - /app/{{ project_name }}.egg-info
      - client:/app/client/dist
    ports:
      - ${PORT:-8000}:8000

  django-migrate:
    <<: *COMMON
    command: /app/.venv/bin/manage.py migrate --noinput
    volumes:
      - .:/app
      - /app/.venv
      - /app/{{ project_name }}.egg-info

volumes:
  client:
  # Postgres
  # pgdata:
